name: Empty String Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-for-empty-strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
