name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: main

      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Build
        run: |
          bun install --frozen-lockfile
        env:
          HUSKY: 0
        if: ${{ steps.release.outputs.release_created }}

      - run: bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        if: ${{ steps.release.outputs.release_created }}
